version: '3'

services:
  order_service:
    build:
      context: ./order_service  # Path to Order Service Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka  # Make sure Kafka is running before Order Service starts

  product_service:
    build:
      context: ./product_service  # Path to Product Service Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - kafka  # Make sure Kafka is running before Product Service starts

  kafka:
    image: bitnami/kafka:3.2.3
    ports:
      - "9092:9092"  # Kafka port
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
